---

- name: Install Apache
  yum: name={{ item }} state=latest
  with_items: httpd{{ apache_version }}

- name: Install Apache modules
  yum: name={{ item }} state=latest
  with_items: apache_packages

- name: Install Apache SSL modules
  yum: name={{ item }} state=latest
  with_items: apache_ssl_packages
  when: apache_usessl|default(false)

