---

- include: users.yml
  when: create_apache_user_with_specific_uid|default(false)

- include: non_defaultdir_pretasks.yml
  when: apache_use_non_defaultdir|default(false)

- include: install.yml

- include: non_defaultdir_tasks.yml
  when: apache_use_non_defaultdir|default(false)

- include: config.yml

- name: Start apache
  service: name={{ apache_service }} state=started enabled=yes
